{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "traefik-dashboard-auth",
    "namespace": "traefik"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "traefik-dashboard-auth",
        "namespace": "traefik"
      }
    },
    "encryptedData": {
      "users": "AgCzHVCZBceXhpugcv/KNXxCmuAIQ1d+fohGwhwKSgN2f12cSZH6dCMtlvDgBUTl34QYtrmOqDMAcSOQtW1g1GcBg1qB6b3tbBryWntiNXQ61GzpYexR6oi1pTRnZQVR/VBgLsiVtLJBFa5jvgtjm00p9oGO5XquwcpoTkwdD1l0JTqi932XJk8Xyk0BBp80nELZDU6OCzv6PlqepgmQe0byboRdN6dyBPgozAIrx0weAiZaxWS0uOxscRYw9KdwxAM82hEP56hu88Ht12BInh9nPicbiL9dBj8vbkbmKZcpMSR8CRjXyOP18vWKkdrDH6lpt6ReMVA/y9uRXac0P3O4CVPtPm+hwZTum3sonh7Nn4vvGrfSQ+9RBSF+TdiBTsE8Y3u0t7s6PjY0+3ObBkjKQjNaaCYTS9swwFx0wwd255rb4rS5W87rXPnHWTxbbmtgSHO9ACmvCL+nhLCashEPHSHxCgI8+AJ6ZFehXWoVo0HpZFDjIsuX6idaiK8dbHMZB+zruLQi0SITFEGmITpJ3qAaR7bHrSV7NrGEZ6P1FnMzHcGk7XHSTdyvw1PoxfH+IWUQ9aCvMkyaknoUjdoymbBvdqSC/BarU5QlM+xdLTTrZG4v3umycfopnrUPMpkvd6H21qtUcILsApCV2YVmdD8AVzbpD2w7ur7Kil8tFTZJTjbzk4U8b3SeW8U/nBZBSN4td3jjL/E2GCdxdLhNbi9ZR4VXPlia"
    }
  }
}
